### ISSUE TITLE
🚀 路线图 & TODO 随笔

### ISSUE THREAD

**Issue by StrayDragon** [StrayDragon/Mine0Vim#3]
项目名称解释为:
- (Mi(**ne)0vim**) => 我的NeoVim配置
- (**Mine**)0(**Vim**) => 我的从零开始的vim配置.

所以我的目标是随时可以在任何一个新环境下快速搭建符合自己口味开发编辑器/IDEs环境. ~(没错, 我就是那种用IDEs也要用Vim Keymap Binding的憨憨😂)~
### 计划包含以下我常用的平台:
> 此列表将在今后逐步支持
- [x] NeoVim 0.4.3+
- [ ] Vim 8.2+
- [ ] IdeaVim (JetBrains IDEs)
- [ ] VSCodeVim (VSCode)

### TODO
> 草稿|记录现有的配置有哪些不足,后续将移动至Github Project管理各个平台需求| `*`越多越优先
#### NeoVim `*****`
- [ ] 语意化的高亮语法插件调整(`semshi`, `nvim-treesitter`)
  - [ ] `semshi` 对 python 的支持要比 `nvim-treesitter` 更细致一些, 调整至**除了py,剩下常用语言使用`nvim-treesitter`**
- [ ] 重构支持(`coc.nvim::CocSearch`, `far.vim`), 这是减少IDEs依赖的重要功能点
- [ ] 大型项目(1w+的源代码的需要的索引同级别)的跳转,引用查看支持
- [ ] 快捷键可视化, 用于README.md引流到Github Page展示, 减轻重复记忆负担
- [ ] 梳理快捷键, 使用 `vim-quickui` 重建快捷键方式, 目标: **按键次数少, 记忆负担小**, 提高效率
  - [ ] 集成 `vim-surround`
  - [ ] 集成 `tabular`
- [ ] (实验) 小项目 debug 支持
- [ ] 悬浮终端中应用与自身交互的配置(`vim-floaterm`)
  - [ ] `lazygit`
- [ ] 插件精简
  - [ ] 开屏`vim-startify`目前只用了`mru`这一个功能, 可以考虑使用CocList或者集成到`vim-quickui`上
- [ ] `asynctask` 深度定制与集成使用
- [ ] `tmux` 交互优化与配置
- [ ] (实验) 不同bundle的配置入口, 用于实现应付不同场景使用不同插件组合的neovim, 有点类似docker那样
- [ ] (实验) 考察 `CocList`, `vim-clap`, `Leaderf`, `fzf.vim`, 其列表的功能优势与不足并取舍

#### Vim `**`
- [ ] 可配置并以兼容模式运行, 舍弃非核心插件与不兼容的插件以及核心配置运行 

#### IdeaVim `*****`
- [x] 迁移并同步配置到本仓库 #5
- [x] 适配热门的核心插件配置 #5 

#### VSCode `***`
- [ ] 迁移并同步部分配置与合并脚本到本仓库
- [ ] 适配热门的核心插件配置
